### ISSUE TITLE
Linked issue hover cards have a bottom border on the box arrow

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#752]
This was a new feature that was just rolled out and can be viewed by hover over https://github.com/StylishThemes/GitHub-Dark/issues/751

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/46691421-e5933280-cbd2-11e8-8716-7e7d4d020900.png)

This is being caused by the rule for `.Popover-message:before`. There's a missing selector rule for `.Popover-message--bottom::before` (and a few others) which makes the bottom border transparent.

* **HTML of the section where the issue occurs**:

````html
<div class="Popover js-hovercard-content position-absolute" style="display: block; outline: none; top: 90.4583px; left: 803.151px;" tabindex="0">
  <div class="Popover-message Popover-message--large Box box-shadow-large Popover-message--bottom-left" style="width:360px;"><div><div class="p-3">
  <div data-hydro-view="{&quot;event_type&quot;:&quot;issue-hovercard-hover&quot;,&quot;payload&quot;:{&quot;pullRequestOrIssueId&quot;:367996763,&quot;subject&quot;:null,&quot;client_id&quot;:&quot;790373834.1527194507&quot;,&quot;originating_request_id&quot;:&quot;CF08:1A45:5390340:976A38F:5BBCF8C0&quot;,&quot;originating_url&quot;:&quot;https://github.com/StylishThemes/GitHub-Dark/issues/751/hovercard&quot;,&quot;user_id&quot;:831974}}" data-hydro-view-hmac="b629053c202531d6e263ada3a099344a3df432a61093eebf42acfd60a50790b1"></div>
  <div class="mb-3 text-small">
    <span class="d-inline-block mr-2">
      <span class="State State--red lh-condensed p-1">
      <svg class="octicon octicon-issue-closed closed text-white" title="Closed" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7 10h2v2H7v-2zm2-6H7v5h2V4zm1.5 1.5l-1 1L12 9l4-4.5-1-1L12 7l-1.5-1.5zM8 13.7A5.71 5.71 0 0 1 2.3 8c0-3.14 2.56-5.7 5.7-5.7 1.83 0 3.45.88 4.5 2.2l.92-.92A6.947 6.947 0 0 0 8 1C4.14 1 1 4.14 1 8s3.14 7 7 7 7-3.14 7-7l-1.52 1.52c-.66 2.41-2.86 4.19-5.48 4.19v-.01z"></path></svg>
      Closed
</span>

    </span>
    <span title="StylishThemes/GitHub-Dark">StylishThemes/GitHub-Dark</span>
    <span class="text-gray-light mx-1">·</span>
    <span class="text-gray-light"><relative-time datetime="2018-10-09T00:20:56Z" title="Oct 8, 2018, 8:20 PM EDT">19 hours ago</relative-time></span>
  </div>
  <h5 class="f5 lh-condensed mt-0 mb-2">
    Danger buttons have the wrong focus color
    <span class="text-normal text-gray-light">#751</span>
  </h5>
    <div class="lh-condensed text-gray mb-3"><p>
<strong>Browser</strong>: chrome
<strong>Operating System</strong>: win10
<strong>URL</strong>: <a href="https://github.com/StylishThemes/GitHub-Dark/settings">https://github.com/StylishThemes/GitHub-Dark/settings</a> &gt; <strong>Danger Zone</strong> section
<strong>Screenshot</strong>:

<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/831974/46639933-12920780-cb37-11e8-9206-542cc0d36bb1.png"></a>
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/831974/46639943-20478d00-cb37-11e8-95ba-d1bc171e7b52.png"></a>

<strong>H…</strong></p></div>
    <div class="d-flex flex-items-center">
        <div>
            
<span class="IssueLabel d-inline-block
      " title="bug :bug:" style="background-color: #ee2222">
  <span class="css-truncate css-truncate-target d-inline-block" style="color: #000000">
    bug <g-emoji class="g-emoji" alias="bug" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f41b.png">🐛</g-emoji>
  </span>
</span>

        </div>
        <span class="d-inline-block text-gray-light mx-2">·</span>
        <div class="d-inline-block clearfix">

          <div class="AvatarStack AvatarStack--left AvatarStack--two col-1 AvatarStack--two col-2">
            <div class="AvatarStack-body tooltipped tooltipped-n" aria-label="xt0rted and Mottie">
                <img src="https://avatars2.githubusercontent.com/u/831974?s=40&amp;v=4" alt="@xt0rted" width="16" height="16" class="avatar">
                <img src="https://avatars0.githubusercontent.com/u/136959?s=40&amp;v=4" alt="@Mottie" width="16" height="16" class="avatar">
            </div>
          </div>
        </div>
    </div>
</div></div></div>
</div>
````

**Comment by Mottie** [comment]
Thanks @xt0rted! It's been fixed in master.

**Comment by xt0rted** [comment]
@silverwind I'm seeing this issue again after yesterday's update. Looks like 2 of the rules removed in d738bf8a66fd9c4dd8f69d1843c5f433cdca1bc6 were added back in f6e2e0bd74c39155202382fcf2f3288611aa45a8 and `.Popover-message:before` is the one causing it. You can see the issue by hovering over any of our names on this page.

**Comment by silverwind** [comment]
These popover bugs are like a whack-a-mole game, you fix one, another pops up. Need to redo our approach, ideally purely through generated styles.

**Comment by the-j0k3r** [comment]
> @silverwind I'm seeing this issue again after yesterday's update.

Hi, and sorry to butt in, but WIndows side Firefox 64 it looks OK.

Happy holidays to everyone. :)

**Comment by the-j0k3r** [comment]
I still cant duplicate this with any chrome based browser or FF. Can we have a retest @xt0rted? =)

**Comment by xt0rted** [comment]
I'm not seeing this anymore either. I think @silverwind fixed it in 558c1652a7da0daa6ef518079394e2e56d1ca6ff but didn't want to tell us.

**Comment by silverwind** [comment]
Yes, likely I forgot about closing this.
